version: '3.9'
services:
  php:
    image: teste
    container_name: php
    restart: always
    volumes:
      - '.:/var/www/html/'
    ports:
      - '80:80'
    links:
      - redis
      - mongodb
    depends_on:
      - mongodb
      - redis
    networks:
      - app