version: '3.9'
services:
  php:
    image: teste
    container_name: php
    restart: always
    volumes:
      - '.:/var/www/html/'
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
      - '${HTTPS_PORT}:${HTTPS_PORT}'
      - '${WEBSOCKET_PORT}:${WEBSOCKET_PORT}'
    links:
      - redis
      - mongodb
    depends_on:
      - mongodb
      - redis
    networks:
      - app